# Config k?t n?i port
server:
  port: 8080
  servlet:
    context-path: /identity
# Config k?t n?i t?i DB
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/identity_service'
    username: root
    password: root
# Config JPA để tự động tạo DB trong thực tế phải tạo bằng SQL
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

jwt:
  signerKey: "but75kvdatab3cqvos454bs761fb6i0y"